### ISSUE TITLE
Response unreadable characters when request OID of MAC Address

### ISSUE THREAD

**Issue by buidanhquy** [tobez/snmp-query-engine#6]
Hi, I can get data about CPU load, uptime, disk space,... But when I try to get MAC Address (OID: 1.3.6.1.2.1.2.2.1.6.2), the response is some unreadable characters like below:

`[ [ '1.3.6.1.2.1.2.2.1.6.2', '�P����' ] ]`

This is my client:

```
var net = require('net');
var msgpack = require("msgpack-lite");

var SERVER_ADDRESS = 'localhost';
var SERVER_PORT = 7667;
var REMOTE_ADDRESS = '192.168.1.110';
var REMOTE_PORT = 161;

var client = new net.Socket();

client.connect(SERVER_PORT, SERVER_ADDRESS, function() {
    console.log('Client connected to: ' + SERVER_ADDRESS + ':' + SERVER_PORT);

    var buffer = msgpack.encode([4, 1, REMOTE_ADDRESS, REMOTE_PORT, [".1.3.6.1.2.1.2.2.1.6.2"]]);
    console.log("Client send: " + buffer);
    client.write(buffer);
});

client.on('data', function(data) {
    console.log("Client receive:");
    console.log(data);
    console.log(msgpack.decode(data)[2]);
    client.destroy();
});

client.on('close', function() {
    console.log('Client closed');
});

client.on('error', function(err) {
    console.error(err);
});
```

Checked with snmp command: 
```
snmpwalk -v2c -c public localhost 1.3.6.1.2.1.2.2.1.6.2
IF-MIB::ifPhysAddress.2 = STRING: 0:c:29:cf:ad:48
```

**Comment by tobez** [comment]
Hello,

SQE only decodes values it receives based on their specified types (meaning it is not aware of the actual MIB types).
This allows it to correctly decode IP addresses, but MAC addresses are simply represented on the wire as Hex-strings,
so you basically get 6 raw bytes back, and you need to decode them yourself.

I’ll get back to you later with a concrete suggestion for your node.js client.

\Anton.

**Comment by tobez** [comment]
You `snmpwalk` example seemingly contradicts what I said previously.  To see it more clearly, run

    snmpwalk -m '' -v2c -c public localhost 1.3.6.1.2.1.2.2.1.6.2

instead.

**Comment by tobez** [comment]
Okay, assuming you use the most recent version of SQE (commit b996f85d5f7834ddc510c9c0bb19d2fb99f1f3c8 or later), which has fixed a couple of issues, you will get a Buffer instead of a broken string, like this:

```
<Buffer 06 00 00 00 00 80>
```

Then, if you have the MAC in a Buffer named `buf`, you can get the MAC string like this:

```javascript
let mac = [];
for (let i = 0; i < 6; i++) {
  mac.push(buf[i].toString(16));
}
console.log(mac.join(':'));
```

resulting in the output

```
6:0:0:0:0:80
```

Hope this helps.
